name: Test-M1
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:

  tests:
    name: "Unit-tests on M1"
    runs-on: macos12.3-m1
    strategy:
      matrix:
        py_vers: [ "3.8"]

    steps:
      - name: Checkout functorch
        uses: actions/checkout@v2
      - name: Install PyTorch Nightly
        shell: arch -arch arm64 bash {0}
        run: |
          python3 -mpip install --pre torch>=1.12.0.dev -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
      - name: Build Functorch and run tests
        shell: arch -arch arm64 bash {0}
        run: |
          python3 setup.py develop

          python3 -m torch.utils.collect_env

          # test_functorch_lagging_op_db.py: Only run this locally because it checks
          # the functorch lagging op db vs PyTorch's op db.
          EXIT_STATUS=0
          find test \( -name test\*.py ! -name test_functorch_lagging_op_db.py \) | xargs -I {} -n 1 python {} -v || EXIT_STATUS=$?
          exit $EXIT_STATUS

